config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'sessions#new'

  resources :reservas
  resources :produtos
  resources :servicos

  resources :clientes
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reserva.rb
class Reserva < ApplicationRecord
    has_many :servicos
    belongs_to :cliente

    validates :servico_id, presence: true
    validates :dataHora, presence: true
    validates :precoTotal, presence: true
    validates :cliente_id, presence: true
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:servico_id, :dataHora)
    end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_form.html.erb
<%= form_with(model: reserva, local: true) do |form| %>
  <% if reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :servico_id %>
    <%= form.collection_select(:servico_id, Servico.order(:nome), :id, :nome, :prompt => true) %>

  </div>

  <div class="field">
    <%= form.label :dataHora %>
    <%= form.datetime_select :dataHora, id: :reserva_dataHora %>
  </div>


  <div class="field">
    <%= form.label :precoTotal %>
    <%= form.text_field :precoTotal, id: :precoTotal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <tr>
      <th>Servico</th>
      <th>Data - Hora</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.servico_id %></td>
        <td><%= reserva.dataHora %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>New Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Servico:</strong>
  <%= @reserva.servico_id %>
</p>

<p>
  <strong>Datahora:</strong>
  <%= @reserva.dataHora %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>