config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'sessions#new'

  resources :reservas
  resources :produtos
  resources :servicos

  resources :clientes
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/servico.rb
class Servico < ApplicationRecord
  has_one :reserva

  validates :nome, presence: true, length: {minimum: 6}
  validates :preco, presence: true, numericality: {only_float: true}, numericality: {greater_than: 0}
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :set_servico, only: [:show, :edit, :update, :destroy]

  # GET /servicos
  # GET /servicos.json
  def index
    @servicos = Servico.all
  end

  # GET /servicos/1
  # GET /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
  end

  # GET /servicos/1/edit
  def edit
  end

  # POST /servicos
  # POST /servicos.json
  def create
    @servico = Servico.new(servico_params)

    respond_to do |format|
      if @servico.save
        format.html { redirect_to @servico, notice: 'Servico was successfully created.' }
        format.json { render :show, status: :created, location: @servico }
      else
        format.html { render :new }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicos/1
  # PATCH/PUT /servicos/1.json
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.html { redirect_to @servico, notice: 'Servico was successfully updated.' }
        format.json { render :show, status: :ok, location: @servico }
      else
        format.html { render :edit }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicos/1
  # DELETE /servicos/1.json
  def destroy
    @servico.destroy
    respond_to do |format|
      format.html { redirect_to servicos_url, notice: 'Servico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servico_params
      params.require(:servico).permit(:nome, :preco, :descricao)
    end
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/servicos/_form.html.erb
<%= form_with(model: servico, local: true) do |form| %>
  <% if servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servico.errors.count, "error") %> prohibited this servico from being saved:</h2>

      <ul>
      <% servico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :servico_nome %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco, id: :servico_preco %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :servico_descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servicos/edit.html.erb
<h1>Editing Servico</h1>

<%= render 'form', servico: @servico %>

<%= link_to 'Show', @servico %> |
<%= link_to 'Back', servicos_path %>

app/views/servicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servicos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preco</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicos.each do |servico| %>
      <tr>
        <td><%= servico.nome %></td>
        <td><%= servico.preco %></td>
        <td><%= servico.descricao %></td>
        <td><%= link_to 'Show', servico %></td>
        <td><%= link_to 'Edit', edit_servico_path(servico) %></td>
        <td><%= link_to 'Destroy', servico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servico', new_servico_path %>

app/views/servicos/new.html.erb
<h1>New Servico</h1>

<%= render 'form', servico: @servico %>

<%= link_to 'Back', servicos_path %>

app/views/servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @servico.nome %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @servico.preco %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @servico.descricao %>
</p>

<%= link_to 'Edit', edit_servico_path(@servico) %> |
<%= link_to 'Back', servicos_path %>