config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'sessions#new'

  resources :reservas
  resources :produtos
  resources :servicos

  resources :clientes
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, presence: true, length: {minimum: 6}
  validates :marca, presence: true
  validates :preco, presence: true, numericality: {only_float: true}, numericality: {greater_than: 0}
  validates :quantidade, presence: true, numericality: {only_integer: true}, numericality: {greater_than: 0}
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :marca, :preco, :quantidade, :descricao)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :produto_nome %>
  </div>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca, id: :produto_marca %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco, id: :produto_preco %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.number_field :quantidade, id: :produto_quantidade %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :produto_descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Marca</th>
      <th>Preco</th>
      <th>Quantidade</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.marca %></td>
        <td><%= produto.preco %></td>
        <td><%= produto.quantidade %></td>
        <td><%= produto.descricao %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @produto.marca %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>