config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'sessions#new'

  resources :reservas
  resources :produtos
  resources :servicos

  resources :clientes
  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>Lugar da Beleza Feminina</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div>
        <nav>
          <ul>
            <% if logged_in? %>
              <li><%= link_to "Reservas", reservas_path %></li>
              <li>
                <ul>
                  <li><%= link_to "Perfil", current_cliente %></li>
                  <li><%= link_to "Editar dados", edit_cliente_path(current_cliente) %></li>

                  <li>
                    <%= link_to "Encerrar Sessão", sign_out_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Iniciar Sessão", root_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="main">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>